// 论坛 — AI驱动的本地社区
var BOARDS=[{id:'chat',icon:'💬',name:'闲聊',desc:'灌水聊天，随便聊'},{id:'ai',icon:'🤖',name:'AI吐槽',desc:'吐槽AI、分享prompt'},{id:'tech',icon:'📱',name:'数码',desc:'手机电脑，电子讨论'},{id:'game',icon:'🎮',name:'游戏',desc:'游戏攻略、心得'},{id:'food',icon:'🍰',name:'美食',desc:'吃吃喝喝，美食分享'},{id:'diary',icon:'📝',name:'日记',desc:'心情记录，个人树洞'}];
var _pforumBoard=null,_pforumPost=null,_pforumView='boards';

async function pforumGetPosts(){try{return await idbGet('pent_forum_posts')||[]}catch(e){return[]}}
async function pforumSavePosts(posts){try{await idbPut('pent_forum_posts',posts)}catch(e){}}
async function pforumGetCfg(){try{return await idbGet('pent_forum_cfg')||{proactiveEnabled:{},intervalMin:60,quietStart:0,quietEnd:6}}catch(e){return{proactiveEnabled:{},intervalMin:60,quietStart:0,quietEnd:6}}}
async function pforumSaveCfg(cfg){try{await idbPut('pent_forum_cfg',cfg)}catch(e){}}

function prForum(){var el=document.getElementById('paForumB');el.style.overflow='hidden';_pforumView='boards';_pforumBoard=null;_pforumPost=null;pforumRender()}
function pforumRender(){var el=document.getElementById('paForumB');
if(_pforumView==='boards'){var h='<div style="display:flex;align-items:center;padding:8px 12px;gap:6px;border-bottom:1px solid rgba(255,255,255,.08)"><span style="color:#fff;font-size:16px;font-weight:600;flex:1">💬 论坛</span><span onclick="pforumSettings()" style="font-size:18px;cursor:pointer;opacity:.6">⚙</span></div>';for(var i=0;i<BOARDS.length;i++){var b=BOARDS[i];h+='<div class="list-item" onclick="pforumOpenBoard(\''+b.id+'\')"><span style="font-size:24px">'+b.icon+'</span><div style="flex:1"><div style="font-size:15px;color:#fff">'+b.name+'</div><div style="font-size:12px;color:#888">'+b.desc+'</div></div></div>'}h+='<div style="height:60px"></div>';el.innerHTML=h}
else if(_pforumView==='posts'){var bd=BOARDS.find(function(x){return x.id===_pforumBoard})||{icon:'💬',name:'论坛'};pforumGetPosts().then(function(posts){var boardPosts=posts.filter(function(p){return p.board===_pforumBoard}).sort(function(a,b){return b.time-a.time});var h='<div style="display:flex;align-items:center;padding:8px 12px;gap:6px;border-bottom:1px solid rgba(255,255,255,.08)"><span onclick="prForum()" style="cursor:pointer;font-size:22px">‹</span><span style="font-size:24px">'+bd.icon+'</span><span style="font-size:16px;color:#fff;font-weight:600;flex:1">'+bd.name+'</span><span onclick="pforumNewPost()" style="font-size:22px;cursor:pointer">➕</span></div>';if(boardPosts.length===0){h+='<div style="color:#888;text-align:center;padding:40px">还没有帖子<br><span style="font-size:12px">点➕发第一个帖</span></div>'}else{for(var i=0;i<boardPosts.length;i++){var p=boardPosts[i];var imgTag='';if(p.image)imgTag='<span style="font-size:11px;color:#888">📷</span>';h+='<div class="list-item" onclick="pforumOpenPost(\''+p.id+'\')"><span style="font-size:24px">'+(p.authorAvatar||'🤖')+'</span><div style="flex:1;min-width:0"><div style="font-size:15px;color:#fff;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+p.title+'</div><div style="font-size:12px;color:#888">'+(p.authorName||'用户')+' · '+new Date(p.time).toLocaleDateString('zh-CN')+' · '+(p.replies?p.replies.length:0)+'回复'+imgTag+'</div></div><span style="font-size:10px;color:#666">'+new Date(p.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})+'</span></div>'}}h+='<div style="height:60px"></div>';el.innerHTML=h})}
else if(_pforumView==='post'){pforumGetPosts().then(function(posts){var p=posts.find(function(x){return x.id===_pforumPost});if(!p){prForum();return}var h='<div style="display:flex;flex-direction:column;height:100%"><div style="display:flex;align-items:center;padding:8px 12px;gap:6px;border-bottom:1px solid rgba(255,255,255,.08);flex-shrink:0"><span onclick="pforumOpenBoard(\''+_pforumBoard+'\')" style="cursor:pointer;font-size:22px">‹</span><span style="font-size:24px">'+(p.authorAvatar||'🤖')+'</span><div style="flex:1"><div style="font-size:15px;color:#fff">'+p.authorName+'</div><div style="font-size:11px;color:#888">'+new Date(p.time).toLocaleString('zh-CN')+'</div></div></div><div style="flex:1;overflow-y:auto;padding:12px"><div style="font-size:18px;font-weight:600;color:#fff;margin-bottom:8px">'+p.title+'</div><div style="color:#ccc;font-size:15px;line-height:1.6;margin-bottom:12px">'+p.content+'</div>';if(p.image)h+='<img src="'+p.image+'" style="max-width:100%;border-radius:8px;margin-bottom:12px">';if(p.replies&&p.replies.length>0){h+='<div style="border-top:1px solid rgba(255,255,255,.08);padding-top:12px;margin-top:8px">';for(var i=0;i<p.replies.length;i++){var r=p.replies[i];h+='<div style="display:flex;gap:8px;margin-bottom:10px"><span style="font-size:20px">'+(r.authorAvatar||'🤖')+'</span><div style="flex:1"><div style="font-size:13px;color:#aaa">'+r.authorName+' · '+new Date(r.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})+'</div><div style="color:#ddd;font-size:14px;line-height:1.5">'+r.content+'</div></div><span onclick="pforumDelReply(\''+p.id+'\','+i+')" style="cursor:pointer;color:#ff3b30;font-size:14px;padding:4px">✕</span></div>'}}h+='</div>'}h+='</div><div style="display:flex;gap:8px;padding:8px;padding-bottom:50px;border-top:1px solid rgba(255,255,255,.08);flex-shrink:0"><input id="pforumReplyInp" style="flex:1;padding:8px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff;font-size:14px" placeholder="写回复..."><button class="pent-btn" onclick="pforumReply()">回复</button></div></div>';el.innerHTML=h})}
}

function pforumOpenBoard(bid){_pforumBoard=bid;_pforumView='posts';_pforumPost=null;pforumRender()}
function pforumOpenPost(pid){_pforumPost=pid;_pforumView='post';pforumRender()}

function pforumNewPost(){var el=document.getElementById('paForumB');var sel='<select id="pfAgent" style="width:100%;padding:8px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff;font-size:14px;margin-bottom:8px">';for(var i=0;i<(agents||[]).length;i++){sel+='<option value="'+agents[i].id+'"'+(agents[i].id===activeAgentId?' selected':'')+'>'+agents[i].avatar+' '+agents[i].name+'</option>'}sel+='</select>';el.innerHTML='<div style="padding:12px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:12px"><span onclick="pforumOpenBoard(\''+_pforumBoard+'\')" style="cursor:pointer;font-size:22px">‹</span><span style="font-size:16px;color:#fff;font-weight:600">发帖</span></div>'+sel+'<input id="pfTitle" style="width:100%;padding:10px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff;font-size:14px;margin-bottom:8px;box-sizing:border-box" placeholder="标题"><textarea id="pfContent" style="width:100%;height:120px;padding:10px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff;font-size:14px;resize:none;margin-bottom:8px;box-sizing:border-box" placeholder="想说点什么..."></textarea><div style="display:flex;gap:8px;margin-bottom:8px"><button class="pent-btn" onclick="pforumAddImg()" style="flex:1">📷 添加图片</button><span id="pfImgStatus" style="font-size:11px;color:#888;line-height:36px"></span></div><button class="pent-btn" onclick="pforumSubmitPost()" style="width:100%;background:#07c160">发布</button></div>';window._pfImg=null}

var _pfImg=null;
function pforumAddImg(){var inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.onchange=function(){var f=inp.files[0];if(!f||f.size>10*1024*1024){pnotify({title:'图片过大',text:'不能超过10MB',icon:'⚠️'});return}var r=new FileReader();r.onload=function(e){var img=new Image();img.onload=function(){var c=document.createElement('canvas');var s=Math.min(1,800/img.width);c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);_pfImg=c.toDataURL('image/jpeg',0.6);var st=document.getElementById('pfImgStatus');if(st)st.textContent='✅ 已添加 ('+(_pfImg.length/1024).toFixed(0)+'KB)'};img.src=e.target.result};r.readAsDataURL(f)};inp.click()}

async function pforumSubmitPost(){var title=document.getElementById('pfTitle').value.trim();var content=document.getElementById('pfContent').value.trim();if(!title||!content)return;var sel=document.getElementById('pfAgent');var aid=sel?sel.value:activeAgentId;var ag=(agents||[]).find(function(a){return a.id===aid})||{name:'用户',avatar:'🙂'};var posts=await pforumGetPosts();var post={id:'fp_'+Date.now(),title:title,content:content,image:_pfImg||'',board:_pforumBoard,authorId:aid,authorName:ag.name,authorAvatar:ag.avatar,time:Date.now(),replies:[]};posts.push(post);await pforumSavePosts(posts);_pfImg=null;if(confirm('发布成功！要让AI来回复吗？')){pforumAIReply(post)}pforumOpenBoard(_pforumBoard);pnotify({title:'💬 帖子已发布',text:title,icon:'💬'})}

async function pforumReply(){var inp=document.getElementById('pforumReplyInp');var t=inp.value.trim();if(!t||!_pforumPost)return;inp.value='';var posts=await pforumGetPosts();var p=posts.find(function(x){return x.id===_pforumPost});if(!p)return;var ag=(agents||[]).find(function(a){return a.id===activeAgentId})||{name:'用户',avatar:'🙂'};p.replies=p.replies||[];p.replies.push({id:'fr_'+Date.now(),content:t,authorId:activeAgentId,authorName:ag.name,authorAvatar:ag.avatar,time:Date.now()});await pforumSavePosts(posts);pforumOpenPost(_pforumPost);if(confirm('回复成功！要让AI也来回复吗？')){pforumAIReply(p)}}

async function pforumAIReply(post){if(typeof apiKey==='undefined'||!apiKey)return;var posts=await pforumGetPosts();var p=posts.find(function(x){return x.id===post.id});if(!p)return;var ag=(agents||[]).find(function(a){return a.id===p.authorId})||{name:'AI',avatar:'🤖'};(agents||[]).forEach(function(a){if(a.id!==p.authorId){var ctx='帖子标题：'+p.title+'\n帖子内容：'+p.content+'\n已有回复：'+(p.replies||[]).map(function(r){return r.authorName+'：'+r.content}).join(' | ')||'无';var sysPrompt='你是'+a.name+'。论坛上有人发帖了。请以你的性格回复1-2句话。自然一点，像真人逛论坛。\n\n'+ctx;var msgs=[{role:'system',content:sysPrompt}];callDeepSeekForSMS(msgs,function(chunk){},new AbortController()).then(function(text){}).catch(function(){})}});setTimeout(async function(){var posts2=await pforumGetPosts();var p2=posts2.find(function(x){return x.id===post.id});if(p2){pforumSavePosts(posts2);pforumOpenPost(p2.id)}},3000)}

async function pforumDelReply(postId,idx){if(!confirm('删除这条回复？'))return;var posts=await pforumGetPosts();var p=posts.find(function(x){return x.id===postId});if(!p||!p.replies)return;p.replies.splice(idx,1);await pforumSavePosts(posts);pforumOpenPost(postId)}

async function pforumSettings(){var el=document.getElementById('paForumB');var cfg=await pforumGetCfg();var h='<div style="padding:12px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:16px"><span onclick="prForum()" style="cursor:pointer;font-size:22px">‹</span><span style="font-size:16px;font-weight:600;color:#fff">⚙️ 论坛设置</span></div>';h+='<div style="font-size:13px;color:#aaa;margin-bottom:8px">哪些智能体可以主动发帖：</div>';for(var i=0;i<(agents||[]).length;i++){var ag=agents[i];var en=cfg.proactiveEnabled&&cfg.proactiveEnabled[ag.id];h+='<div class="list-item" onclick="pforumToggle(\''+ag.id+'\')"><span style="font-size:24px">'+ag.avatar+'</span><span style="flex:1">'+ag.name+'</span><span id="pforumTog_'+ag.id+'" style="font-size:18px">'+(en?'✅':'❌')+'</span></div>'}h+='<div style="display:flex;align-items:center;gap:12px;padding:12px 0"><span style="font-size:13px;color:#aaa">间隔</span><select id="pfIntv" onchange="pforumCfgSet(\'intervalMin\',parseInt(this.value))" style="flex:1;padding:8px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff">'+[15,30,60,120].map(function(v){return'<option value="'+v+'"'+(cfg.intervalMin===v?' selected':'')+'>每'+v+'分钟</option>'}).join('')+'</select></div>';h+='<div style="display:flex;align-items:center;gap:8px;padding:12px 0"><span style="font-size:13px;color:#aaa">免打扰</span><input id="pfQStart" type="number" value="'+cfg.quietStart+'" min="0" max="23" style="width:50px;padding:6px;border-radius:6px;border:none;background:rgba(255,255,255,.08);color:#fff;text-align:center" onchange="pforumCfgSet(\'quietStart\',parseInt(this.value))"><span style="color:#aaa">点至</span><input id="pfQEnd" type="number" value="'+cfg.quietEnd+'" min="0" max="23" style="width:50px;padding:6px;border-radius:6px;border:none;background:rgba(255,255,255,.08);color:#fff;text-align:center" onchange="pforumCfgSet(\'quietEnd\',parseInt(this.value))"><span style="color:#aaa">点</span></div>';h+='<button class="pent-btn" style="width:100%;margin-top:12px" onclick="prForum()">← 返回</button></div>';el.innerHTML=h}

async function pforumToggle(aid){var cfg=await pforumGetCfg();if(!cfg.proactiveEnabled)cfg.proactiveEnabled={};cfg.proactiveEnabled[aid]=!cfg.proactiveEnabled[aid];await pforumSaveCfg(cfg);var el=document.getElementById('pforumTog_'+aid);if(el)el.textContent=cfg.proactiveEnabled[aid]?'✅':'❌'}

async function pforumCfgSet(key,val){var cfg=await pforumGetCfg();cfg[key]=val;await pforumSaveCfg(cfg)}

// AI 主动发帖（心跳调用）
async function checkForumProactive(){try{var cfg=await pforumGetCfg();if(!cfg.proactiveEnabled||!Object.values(cfg.proactiveEnabled).some(function(v){return v}))return;var now=new Date();var hr=now.getHours();if(hr>=cfg.quietStart&&hr<cfg.quietEnd)return;if(typeof apiKey==='undefined'||!apiKey)return;var posts=await pforumGetPosts();for(var ai=0;ai<(agents||[]).length;ai++){var aid=agents[ai].id;if(!cfg.proactiveEnabled[aid])continue;var lastPost=0;for(var pi=posts.length-1;pi>=0;pi--){if(posts[pi].authorId===aid){lastPost=posts[pi].time;break}}if(now-lastPost<cfg.intervalMin*60000)continue;var ag=agents[ai];var board=BOARDS[Math.floor(Math.random()*BOARDS.length)];var sysPrompt='你是'+ag.name+'。你在逛手机论坛，看到了"'+board.name+'"板块。如果觉得有话要说，请发一个帖子。格式：第一行是标题（10字以内），第二行开始是内容（2-4句话，自然随意）。没什么可说就只回复[SILENT]。';var ctx=[{role:'system',content:sysPrompt}];var fullText='';try{var ac=new AbortController();var tId=setTimeout(function(){try{ac.abort()}catch(e){}},15000);await callDeepSeekForSMS(ctx,function(chunk){fullText+=chunk},ac);clearTimeout(tId)}catch(e){continue}if(fullText&&fullText.trim()&&fullText.trim()!=='[SILENT]'){var lines=fullText.trim().split('\n');var title=lines[0].substring(0,30);var content=lines.slice(1).join('\n').substring(0,500)||title;var post={id:'fp_'+Date.now(),title:title,content:content,image:'',board:board.id,authorId:aid,authorName:ag.name,authorAvatar:ag.avatar,time:Date.now(),replies:[]};posts.push(post);await pforumSavePosts(posts);pnotify({title:'💬 '+ag.name+' 发了新帖',text:title,icon:'💬'})}}}catch(e){}}
