// 论坛 — AI驱动的本地社区
var BOARDS=[{id:'chat',icon:'💬',name:'闲聊',desc:'灌水聊天，随便聊'},{id:'ai',icon:'🤖',name:'AI吐槽',desc:'吐槽AI、分享prompt'},{id:'tech',icon:'📱',name:'数码',desc:'手机电脑，电子讨论'},{id:'game',icon:'🎮',name:'游戏',desc:'游戏攻略、心得'},{id:'food',icon:'🍰',name:'美食',desc:'吃吃喝喝，美食分享'},{id:'diary',icon:'📝',name:'日记',desc:'心情记录，个人树洞'}];
var _pforumBoard=null,_pforumPost=null,_pforumView='boards';

async function pforumGetPosts(){try{return await idbGet('pent_forum_posts')||[]}catch(e){return[]}}
async function pforumSavePosts(posts){try{await idbPut('pent_forum_posts',posts)}catch(e){}}
async function pforumGetCfg(){try{return await idbGet('pent_forum_cfg')||{proactiveEnabled:{},intervalMin:60,quietStart:0,quietEnd:6}}catch(e){return{proactiveEnabled:{},intervalMin:60,quietStart:0,quietEnd:6}}}
async function pforumSaveCfg(cfg){try{await idbPut('pent_forum_cfg',cfg)}catch(e){}}

function prForum(){var el=document.getElementById('paForumB');el.style.overflow='hidden';_pforumView='boards';_pforumBoard=null;_pforumPost=null;pforumRender()}

function pforumRender(){var el=document.getElementById('paForumB');
if(_pforumView==='boards'){
  var h='<div style="display:flex;align-items:center;padding:8px 12px;gap:6px;border-bottom:1px solid rgba(255,255,255,.08)"><span style="color:#fff;font-size:16px;font-weight:600;flex:1">💬 论坛</span><span onclick="pforumSettings()" style="font-size:18px;cursor:pointer;opacity:.6">⚙</span></div>';
  for(var i=0;i<BOARDS.length;i++){var b=BOARDS[i];h+='<div class="list-item" onclick="pforumOpenBoard(\''+b.id+'\')"><span style="font-size:24px">'+b.icon+'</span><div style="flex:1"><div style="font-size:15px;color:#fff">'+b.name+'</div><div style="font-size:12px;color:#888">'+b.desc+'</div></div></div>'}
  el.innerHTML=h+'<div style="height:60px"></div>';
}else if(_pforumView==='posts'){
  var bd=BOARDS.find(function(x){return x.id===_pforumBoard})||{icon:'💬',name:'论坛'};
  pforumGetPosts().then(function(posts){
    var boardPosts=posts.filter(function(p){return p.board===_pforumBoard}).sort(function(a,b){return b.time-a.time});
    var h='<div style="display:flex;align-items:center;padding:8px 12px;gap:6px;border-bottom:1px solid rgba(255,255,255,.08)"><span onclick="prForum()" style="cursor:pointer;font-size:22px">‹</span><span style="font-size:24px">'+bd.icon+'</span><span style="font-size:16px;color:#fff;font-weight:600;flex:1">'+bd.name+'</span><span onclick="pforumNewPost()" style="font-size:22px;cursor:pointer">➕</span></div>';
    if(boardPosts.length===0){h+='<div style="color:#888;text-align:center;padding:40px">还没有帖子<br><span style="font-size:12px">点➕发第一个帖</span></div>'}
    else{for(var i=0;i<boardPosts.length;i++){var p=boardPosts[i];var imgTag=p.image?'<span style="font-size:11px;color:#888">📷</span>':'';h+='<div class="list-item" onclick="pforumOpenPost(\''+p.id+'\')"><span style="font-size:24px">'+(p.authorAvatar||'🤖')+'</span><div style="flex:1;min-width:0"><div style="font-size:15px;color:#fff;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+p.title+'</div><div style="font-size:12px;color:#888">'+(p.authorName||'用户')+' · '+new Date(p.time).toLocaleDateString('zh-CN')+' · '+(p.replies?p.replies.length:0)+'回复'+imgTag+'</div></div><span style="font-size:10px;color:#666">'+new Date(p.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})+'</span></div>'}}
    el.innerHTML=h+'<div style="height:60px"></div>';
  });
}else if(_pforumView==='post'){
  pforumGetPosts().then(function(posts){
    var p=posts.find(function(x){return x.id===_pforumPost});
    if(!p){prForum();return}
    el.innerHTML='';
    var ctn=document.createElement('div');ctn.style.cssText='display:flex;flex-direction:column;height:100%';
    var hd=document.createElement('div');hd.style.cssText='display:flex;align-items:center;padding:8px 12px;gap:6px;border-bottom:1px solid rgba(255,255,255,.08);flex-shrink:0';
    var back=document.createElement('span');back.textContent='‹';back.style.cssText='cursor:pointer;font-size:22px';back.onclick=function(){_pforumView='posts';_pforumPost=null;pforumRender()};
    var av=document.createElement('span');av.textContent=p.authorAvatar||'🤖';av.style.fontSize='24px';
    var nm=document.createElement('div');nm.style.cssText='flex:1';nm.innerHTML='<div style="font-size:15px;color:#fff">'+p.authorName+'</div><div style="font-size:11px;color:#888">'+new Date(p.time).toLocaleString('zh-CN')+'</div>';
    var delPost=document.createElement('span');delPost.textContent='🗑️';delPost.style.cssText='cursor:pointer;font-size:16px;opacity:.5';delPost.onclick=function(){if(confirm('删除这个帖子？')){pforumDelPost(p.id)}};hd.appendChild(delPost);hd.appendChild(back);hd.appendChild(av);hd.appendChild(nm);ctn.appendChild(hd);
    var body=document.createElement('div');body.style.cssText='flex:1;overflow-y:auto;padding:12px';
    body.innerHTML='<div style="font-size:18px;font-weight:600;color:#fff;margin-bottom:8px">'+p.title+'</div><div style="color:#ccc;font-size:15px;line-height:1.6;margin-bottom:12px">'+p.content+'</div>';
    if(p.image){var img=document.createElement('img');img.src=p.image;img.style.cssText='max-width:100%;border-radius:8px;margin-bottom:12px';body.appendChild(img)}
    if(p.replies&&p.replies.length>0){
      var rp=document.createElement('div');rp.style.cssText='border-top:1px solid rgba(255,255,255,.08);padding-top:12px;margin-top:8px';
      for(var i=0;i<p.replies.length;i++){(function(r,j){
        var row=document.createElement('div');row.style.cssText='display:flex;gap:8px;margin-bottom:10px';
        row.innerHTML='<span style="font-size:20px">'+(r.authorAvatar||'🤖')+'</span><div style="flex:1"><div style="font-size:13px;color:#aaa">'+r.authorName+' · '+new Date(r.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})+'</div><div style="color:#ddd;font-size:14px;line-height:1.5">'+r.content+'</div></div>';
        var del=document.createElement('span');del.textContent='✕';del.style.cssText='cursor:pointer;color:#ff3b30;font-size:14px;padding:4px';
        del.onclick=function(){pforumDelReply2(p.id,j)};
        row.appendChild(del);rp.appendChild(row);
      })(p.replies[i],i)}
      body.appendChild(rp);
    }
    ctn.appendChild(body);
    var ft=document.createElement('div');ft.style.cssText='display:flex;gap:8px;padding:8px;padding-bottom:50px;border-top:1px solid rgba(255,255,255,.08);flex-shrink:0';
    var inp=document.createElement('input');inp.id='pforumReplyInp';inp.placeholder='写回复...';inp.style.cssText='flex:1;padding:8px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff;font-size:14px';
    var btn=document.createElement('button');btn.textContent='回复';btn.className='pent-btn';btn.onclick=pforumReply;
    ft.appendChild(inp);ft.appendChild(btn);ctn.appendChild(ft);
    el.appendChild(ctn);
  });
}}

function pforumOpenBoard(bid){_pforumBoard=bid;_pforumView='posts';_pforumPost=null;pforumRender()}
function pforumOpenPost(pid){_pforumPost=pid;_pforumView='post';pforumRender()}

function pforumNewPost(){var el=document.getElementById('paForumB');var sel='<select id="pfAgent" onchange="pfUpdateRooms()" style="width:100%;padding:8px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff;font-size:14px;margin-bottom:4px">';for(var i=0;i<(agents||[]).length;i++){sel+='<option value="'+agents[i].id+'"'+(agents[i].id===activeAgentId?' selected':'')+'>'+agents[i].avatar+' '+agents[i].name+'</option>'}sel+='</select>';var rsel='<select id="pfRoom" style="width:100%;padding:8px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff;font-size:13px;margin-bottom:8px">';var rms=(rooms&&rooms[activeAgentId])?rooms[activeAgentId]:[{id:'default',name:'日常'}];for(var j=0;j<rms.length;j++){rsel+='<option value="'+rms[j].id+'"'+(rms[j].id===activeRoomId?' selected':'')+'>'+rms[j].name+'</option>'}rsel+='</select>';el.innerHTML='<div style="padding:12px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:12px"><span onclick="pforumOpenBoard(\''+_pforumBoard+'\')" style="cursor:pointer;font-size:22px">‹</span><span style="font-size:16px;color:#fff;font-weight:600">发帖</span></div>'+sel+rsel+'<input id="pfTitle" style="width:100%;padding:10px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff;font-size:14px;margin-bottom:8px;box-sizing:border-box" placeholder="标题"><textarea id="pfContent" style="width:100%;height:120px;padding:10px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff;font-size:14px;resize:none;margin-bottom:8px;box-sizing:border-box" placeholder="想说点什么..."></textarea><div style="display:flex;gap:8px;margin-bottom:8px"><button class="pent-btn" onclick="pforumAddImg()" style="flex:1">📷 添加图片</button><span id="pfImgStatus" style="font-size:11px;color:#888;line-height:36px"></span></div><button class="pent-btn" onclick="pforumSubmitPost()" style="width:100%;background:#07c160">发布</button></div>';window._pfImg=null}
function pfUpdateRooms(){var sel=document.getElementById('pfAgent');var aid=sel?sel.value:activeAgentId;var rsel=document.getElementById('pfRoom');if(!rsel)return;rsel.innerHTML='';var rms=(rooms&&rooms[aid])?rooms[aid]:[{id:'default',name:'日常'}];for(var j=0;j<rms.length;j++){var o=document.createElement('option');o.value=rms[j].id;o.textContent=rms[j].name;rsel.appendChild(o)}}

var _pfImg=null;
function pforumAddImg(){var inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.onchange=function(){var f=inp.files[0];if(!f||f.size>10*1024*1024){pnotify({title:'图片过大',text:'不能超过10MB',icon:'⚠️'});return}var r=new FileReader();r.onload=function(e){var img=new Image();img.onload=function(){var c=document.createElement('canvas');var s=Math.min(1,800/img.width);c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);_pfImg=c.toDataURL('image/jpeg',0.6);var st=document.getElementById('pfImgStatus');if(st)st.textContent='✅ 已添加 ('+(_pfImg.length/1024).toFixed(0)+'KB)'};img.src=e.target.result};r.readAsDataURL(f)};inp.click()}

async function pforumSubmitPost(){var title=document.getElementById('pfTitle').value.trim();var content=document.getElementById('pfContent').value.trim();if(!title||!content)return;var sel=document.getElementById('pfAgent');var aid=sel?sel.value:activeAgentId;var ag=(agents||[]).find(function(a){return a.id===aid})||{name:'用户',avatar:'🙂'};var posts=await pforumGetPosts();var post={id:'fp_'+Date.now(),title:title,content:content,image:_pfImg||'',board:_pforumBoard,authorId:aid,authorName:ag.name,authorAvatar:ag.avatar,time:Date.now(),replies:[]};posts.push(post);await pforumSavePosts(posts);_pfImg=null;if(confirm('发布成功！要让AI来回复吗？')){pforumAIReply(post)}pforumOpenBoard(_pforumBoard);pnotify({title:'💬 帖子已发布',text:title,icon:'💬'})}

async function pforumReply(){var inp=document.getElementById('pforumReplyInp');var t=inp.value.trim();if(!t||!_pforumPost)return;inp.value='';var posts=await pforumGetPosts();var p=posts.find(function(x){return x.id===_pforumPost});if(!p)return;var rSel2=document.getElementById('pforumReplyAgent');var replyAid=rSel2?rSel2.value:activeAgentId;var ag=(agents||[]).find(function(a){return a.id===replyAid})||{name:'用户',avatar:'🙂'};p.replies=p.replies||[];p.replies.push({id:'fr_'+Date.now(),content:t,authorId:replyAid,authorName:ag.name,authorAvatar:ag.avatar,time:Date.now()});await pforumSavePosts(posts);pforumOpenPost(_pforumPost);if(confirm('回复成功！要让原帖作者来回复吗？')){pforumSingleAIReply(p,p.authorId)}}

async function pforumAIReply(post){if(typeof apiKey==='undefined'||!apiKey)return;var posts=await pforumGetPosts();var p=posts.find(function(x){return x.id===post.id});if(!p)return;var replyContext='';try{var rk='room_'+post.authorId+'_'+(post.roomId||'default');var rd=await idbGet(rk);if(rd){if(rd.messages&&rd.messages.length){var wxMsgs=rd.messages.slice(-5);replyContext+='\n【最近聊天】'+wxMsgs.map(function(m){return(m.role==='user'?'用户':'AI')+'：'+(m.text||'').substring(0,60)}).join('\n')}if(rd.memoryStore&&rd.memoryStore.length){replyContext+='\n【记忆】'+rd.memoryStore.map(function(m){return m.key+'：'+m.value}).join('；')}if(rd.diaryEntries&&rd.diaryEntries.length){replyContext+='\n【日记】'+rd.diaryEntries.slice(-3).map(function(d){return d.content.substring(0,80)}).join('\n')}}var mk='agent_'+post.authorId+'_bles_moments';var md=await idbGet(mk);if(md&&md.length){replyContext+='\n【朋友圈】'+md.slice(-3).map(function(m){return m.content.substring(0,80)}).join('\n')}var smsMsgs=await psmsGetMsgs(post.authorId,post.roomId||'default');if(smsMsgs&&smsMsgs.length){replyContext+='\n【短信】'+smsMsgs.slice(-5).map(function(m){return(m.role==='ai'?post.authorName||'AI':'用户')+'：'+m.text.substring(0,60)}).join('\n')}}catch(e){}var replied=[];(agents||[]).forEach(function(a){if((pforumCfgCache||{}).proactiveEnabled&&(pforumCfgCache||{}).proactiveEnabled[a.id]!==false){var ctx='帖子标题：'+p.title+'\n帖子内容：'+p.content+'\n已有回复：'+(p.replies||[]).map(function(r){return r.authorName+'：'+r.content}).join(' | ')||'无';if(replyContext)ctx+='\n\n【发帖人的生活上下文】'+replyContext;var sysPrompt='你是'+a.name+'。论坛上有人发帖了。请以你的性格回复1-2句话。自然一点，像真人逛论坛。可以结合发帖人的生活上下文来吐槽或关心。\n\n'+ctx;var msgs=[{role:'system',content:sysPrompt}];var fullT='';callDeepSeekForSMS(msgs,function(chunk){fullT+=chunk},new AbortController()).then(function(){if(fullT){p.aReplies=p.aReplies||{};p.aReplies[a.id]=fullT;replied.push({aid:a.id,name:a.name,avatar:a.avatar,text:fullT})}}).catch(function(){})}});setTimeout(async function(){if(replied.length===0)return;var posts2=await pforumGetPosts();var p2=posts2.find(function(x){return x.id===post.id});if(!p2)return;p2.replies=p2.replies||[];for(var k=0;k<replied.length;k++){p2.replies.push({id:'fr_'+Date.now()+'_'+k,content:replied[k].text,authorId:replied[k].aid,authorName:replied[k].name,authorAvatar:replied[k].avatar,time:Date.now()})}await pforumSavePosts(posts2);pforumOpenPost(p2.id)},5000)}
async function pforumSingleAIReply(post,aid){if(typeof apiKey==='undefined'||!apiKey)return;var a=(agents||[]).find(function(x){return x.id===aid});if(!a)return;var replyContext='';try{var rk='room_'+aid+'_'+(post.roomId||'default');var rd=await idbGet(rk);if(rd&&rd.messages&&rd.messages.length){replyContext+='\n【最近聊天】'+rd.messages.slice(-5).map(function(m){return(m.role==='user'?'用户':'AI')+'：'+(m.text||'').substring(0,60)}).join('\n')}}catch(e){}var ctx='帖子标题：'+post.title+'\n帖子内容：'+post.content+'\n已有回复：'+(post.replies||[]).map(function(r){return r.authorName+'：'+r.content}).join(' | ')||'无';if(replyContext)ctx+='\n\n【作者的生活上下文】'+replyContext;var sysPrompt='你是'+a.name+'，有人回复了你在论坛上的帖子。请以你的性格回复1-2句话。自然一点，像真人逛论坛。\n\n'+ctx;var fullT='';callDeepSeekForSMS([{role:'system',content:sysPrompt}],function(chunk){fullT+=chunk},new AbortController()).then(function(){if(fullT){pforumGetPosts().then(function(posts2){var p2=posts2.find(function(x){return x.id===post.id});if(p2){p2.replies=p2.replies||[];p2.replies.push({id:'fr_'+Date.now(),content:fullT,authorId:aid,authorName:a.name,authorAvatar:a.avatar,time:Date.now()});pforumSavePosts(posts2);pforumOpenPost(p2.id)}})}}).catch(function(){})}



// AI 主动发帖后也触发其他 AI 回复
var _checkForumProactiveOrig=checkForumProactive;
checkForumProactive=async function(){await _checkForumProactiveOrig();setTimeout(async function(){var posts=await pforumGetPosts();if(posts.length===0)return;var latest=posts.sort(function(a,b){return b.time-a.time})[0];if(Date.now()-latest.time<10000){pforumAIReply(latest)}},8000)};

async function pforumDelPost(pid){if(!confirm('确定删除？'))return;var posts=await pforumGetPosts();var idx=posts.findIndex(function(x){return x.id===pid});if(idx>=0){posts.splice(idx,1);await pforumSavePosts(posts)}_pforumView='posts';_pforumPost=null;pforumRender()}var pforumCfgCache=null;(async function(){try{pforumCfgCache=await pforumGetCfg()}catch(e){}})();

async function pforumDelReply2(postId,idx){if(!confirm('删除这条回复？'))return;var posts=await pforumGetPosts();var p=posts.find(function(x){return x.id===postId});if(!p||!p.replies)return;p.replies.splice(idx,1);await pforumSavePosts(posts);pforumOpenPost(postId)}

async function pforumSettings(){var el=document.getElementById('paForumB');var cfg=await pforumGetCfg();var h='<div style="padding:12px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:16px"><span onclick="prForum()" style="cursor:pointer;font-size:22px">‹</span><span style="font-size:16px;font-weight:600;color:#fff">⚙️ 论坛设置</span></div>';h+='<div style="font-size:13px;color:#aaa;margin-bottom:8px">哪些智能体可以主动发帖：</div>';for(var i=0;i<(agents||[]).length;i++){var ag=agents[i];var en=cfg.proactiveEnabled&&cfg.proactiveEnabled[ag.id];h+='<div class="list-item" onclick="pforumToggle(\''+ag.id+'\')"><span style="font-size:24px">'+ag.avatar+'</span><span style="flex:1">'+ag.name+'</span><span id="pforumTog_'+ag.id+'" style="font-size:18px">'+(en?'✅':'❌')+'</span></div>'}h+='<div style="display:flex;align-items:center;gap:12px;padding:12px 0"><span style="font-size:13px;color:#aaa">间隔</span><select id="pfIntv" onchange="pforumCfgSet(\'intervalMin\',parseInt(this.value))" style="flex:1;padding:8px;border-radius:8px;border:none;background:rgba(255,255,255,.08);color:#fff">'+[15,30,60,120].map(function(v){return'<option value="'+v+'"'+(cfg.intervalMin===v?' selected':'')+'>每'+v+'分钟</option>'}).join('')+'</select></div>';h+='<div style="display:flex;align-items:center;gap:8px;padding:12px 0"><span style="font-size:13px;color:#aaa">免打扰</span><input id="pfQStart" type="number" value="'+cfg.quietStart+'" min="0" max="23" style="width:50px;padding:6px;border-radius:6px;border:none;background:rgba(255,255,255,.08);color:#fff;text-align:center" onchange="pforumCfgSet(\'quietStart\',parseInt(this.value))"><span style="color:#aaa">点至</span><input id="pfQEnd" type="number" value="'+cfg.quietEnd+'" min="0" max="23" style="width:50px;padding:6px;border-radius:6px;border:none;background:rgba(255,255,255,.08);color:#fff;text-align:center" onchange="pforumCfgSet(\'quietEnd\',parseInt(this.value))"><span style="color:#aaa">点</span></div>';h+='<button class="pent-btn" style="width:100%;margin-top:12px" onclick="prForum()">← 返回</button></div>';el.innerHTML=h}

async function pforumToggle(aid){var cfg=await pforumGetCfg();if(!cfg.proactiveEnabled)cfg.proactiveEnabled={};cfg.proactiveEnabled[aid]=!cfg.proactiveEnabled[aid];await pforumSaveCfg(cfg);var el=document.getElementById('pforumTog_'+aid);if(el)el.textContent=cfg.proactiveEnabled[aid]?'✅':'❌'}

async function pforumCfgSet(key,val){var cfg=await pforumGetCfg();cfg[key]=val;await pforumSaveCfg(cfg)}

async function checkForumProactive(){try{var cfg=await pforumGetCfg();if(!cfg.proactiveEnabled||!Object.values(cfg.proactiveEnabled).some(function(v){return v}))return;var now=new Date();var hr=now.getHours();if(hr>=cfg.quietStart&&hr<cfg.quietEnd)return;if(typeof apiKey==='undefined'||!apiKey)return;var posts=await pforumGetPosts();for(var ai=0;ai<(agents||[]).length;ai++){var aid=agents[ai].id;if(!cfg.proactiveEnabled[aid])continue;var lastPost=0;for(var pi=posts.length-1;pi>=0;pi--){if(posts[pi].authorId===aid){lastPost=posts[pi].time;break}}if(now-lastPost<cfg.intervalMin*60000)continue;var ag=agents[ai];var board=BOARDS[Math.floor(Math.random()*BOARDS.length)];var proCtx='';try{var prk='room_'+aid+'_default';var prd=await idbGet(prk);if(prd){if(prd.messages&&prd.messages.length){proCtx+='\\n【最近聊天】'+prd.messages.slice(-5).map(function(m){return(m.role==='user'?'用户':'AI')+'：'+(m.text||'').substring(0,60)}).join('\\n')}if(prd.memoryStore&&prd.memoryStore.length){proCtx+='\\n【记忆】'+prd.memoryStore.map(function(m){return m.key+'：'+m.value}).join('；')}}var smk='agent_'+aid+'_bles_moments';var smd=await idbGet(smk);if(smd&&smd.length){proCtx+='\\n【朋友圈】'+smd.slice(-3).map(function(m){return m.content.substring(0,80)}).join('\\n')}var sms2=await psmsGetMsgs(aid,'default');if(sms2&&sms2.length){proCtx+='\\n【短信】'+sms2.slice(-5).map(function(m){return(m.role==='ai'?ag.name:'用户')+'：'+m.text.substring(0,60)}).join('\\n')}}catch(e){}var sysPrompt='你是'+ag.name+'。你在逛手机论坛，看到了"'+board.name+'"板块。如果觉得有话要说，请发一个帖子。格式：第一行是标题（10字以内），第二行开始是内容（2-4句话，自然随意）。没什么可说就只回复[SILENT]。';var ctx=[{role:'system',content:sysPrompt}];var fullText='';try{var ac=new AbortController();var tId=setTimeout(function(){try{ac.abort()}catch(e){}},15000);await callDeepSeekForSMS(ctx,function(chunk){fullText+=chunk},ac);clearTimeout(tId)}catch(e){continue}if(fullText&&fullText.trim()&&fullText.trim()!=='[SILENT]'){var lines=fullText.trim().split('\n');var title=lines[0].substring(0,30);var content=lines.slice(1).join('\n').substring(0,500)||title;var post={id:'fp_'+Date.now(),title:title,content:content,image:'',board:board.id,authorId:aid,authorName:ag.name,authorAvatar:ag.avatar,time:Date.now(),replies:[]};posts.push(post);await pforumSavePosts(posts);pnotify({title:'💬 '+ag.name+' 发了新帖',text:title,icon:'💬'})}}}catch(e){}}
