async function paddMusic(){var inp=document.createElement('input');inp.type='file';inp.accept='audio/*,video/*';inp.onchange=async function(){var f=inp.files[0];if(!f)return;if(f.size>200*1024*1024){pnotify({title:'文件过大',text:'不能超过 200MB',icon:'⚠️'});return}pnotify({title:'⏳ 导入中...',text:f.name,icon:'🎵'});var r=new FileReader();r.onload=async function(e){var a=[];try{a=await idbGet('pent_music')||[]}catch(ex){}a.unshift({name:f.name,size:f.size,data:e.target.result,src:'',time:Date.now()});if(a.length>100)a=a.slice(0,100);await idbPut('pent_music',a);prMusic();pnotify({title:'🎵 已导入',text:f.name,icon:'🎵'})};r.readAsDataURL(f)};inp.click()}
function paddMusicURL(){var url=prompt('粘贴链接（网易云·QQ音乐·酷狗·酷我·B站·YouTube·抖音·直链）:');if(!url||!url.trim())return;url=url.trim();var name='',type='',src='',ext='';var m163=url.match(/music\.163\.com.*[?&;]id=(\d+)/i);var mQQ=url.match(/y\.qq\.com.*song(?:Detail|id)[=/](\w+)/i)||url.match(/i\.y\.qq\.com.*songmid=(\w+)/i);var mKG=url.match(/kugou\.com.*[?&;]hash=([A-F0-9]+)/i)||url.match(/kugou\.com\/song\/.*hash=([A-F0-9]+)/i)||url.match(/t\d\.kugou\.com\/(\w+)/i);var mKW=url.match(/kuwo\.cn\/\w+/i)||url.match(/kuwo\.com.*(?:rid|musicid)=(\d+)/i);var mBili=url.match(/bilibili\.com\/video\/(BV\w+)/i)||url.match(/b23\.tv\/(\w+)/i);var mYT=url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/i);var mDY=url.match(/douyin\.com\/video\/(\d+)/i)||url.match(/v\.douyin\.com\/(\w+)/i);if(m163){var id=m163[1];name='🎶 网易云 #'+id;type='netease';src='https://music.163.com/outchain/player?type=2&id='+id+'&auto=0&height=66'}else if(mQQ){var sid=mQQ[1];name='🎶 QQ音乐 '+sid;type='qqmusic';src='https://i.y.qq.com/v8/playsong.html?songmid='+sid+'&source=yqq'}else if(mKG){var kgHash=mKG[1];name='🎶 酷狗 '+kgHash;type='kugou';src='https://www.kugou.com/song/#hash='+kgHash} else if(mKW){var kwId=mKW[1]||mKW[0];name='🎶 酷我 '+kwId;type='kuwo';src='https://www.kuwo.cn/play_detail/'+kwId}else if(mBili){var bv=mBili[1];name='🎬 B站 '+bv;type='bilibili';src='https://player.bilibili.com/player.html?bvid='+bv+'&autoplay=0'}else if(mYT){var ytId=mYT[1];name='🎬 YouTube '+ytId;type='youtube';src='https://www.youtube.com/embed/'+ytId}else if(mDY){var dyId=mDY[1]||mDY[0];name='🎬 抖音 '+dyId;type='douyin';src=url}else{name=url.split('/').pop().split('?')[0]||'在线资源';if(!/\.(mp3|wav|ogg|flac|aac|m4a|mp4|webm|mov|mkv|avi|wmv|flv)/i.test(name))name+='.mp3';type='direct';src=url}(async function(){var a=[];try{a=await idbGet('pent_music')||[]}catch(ex){}a.unshift({name:name,size:0,data:'',src:src,type:type,time:Date.now()});if(a.length>100)a=a.slice(0,100);await idbPut('pent_music',a);prMusic();var icons={netease:'🎶',qqmusic:'🎶',kugou:'🎶',kuwo:'🎶',bilibili:'🎬',youtube:'🎬',douyin:'🎬',direct:'🎵'};pnotify({title:'🔗 已添加',text:name,icon:icons[type]||'🎵'})})()}
async function pdelTrack(i){var a=[];try{a=await idbGet('pent_music')||[]}catch(ex){}a.splice(i,1);await idbPut('pent_music',a);if(_pcurTrack===i){pstop();_pcurTrack=null}else if(_pcurTrack>i)_pcurTrack--;prMusic()}
async function pplayTrack(i){var a=[];try{a=await idbGet('pent_music')||[]}catch(ex){}var t=a[i];if(!t)return;_pcurTrack=i;pstop();var vt=t.type||'';if(vt==='netease'||vt==='qqmusic'){document.getElementById('pmVid').style.display='block';document.getElementById('pmVid').innerHTML='<iframe src="'+t.src+'" width="100%" height="66" frameborder="0" style="border-radius:8px"></iframe>';_pAudio=null;document.getElementById('pmPlayBtn').textContent='▶️'}else if(vt==='bilibili'||vt==='youtube'){document.getElementById('pmVid').style.display='block';document.getElementById('pmVid').innerHTML='<iframe src="'+t.src+'" width="100%" style="aspect-ratio:16/9;border-radius:8px" frameborder="0" allowfullscreen></iframe>';_pAudio=null;document.getElementById('pmPlayBtn').textContent='▶️'}else if(vt==='kugou'||vt==='kuwo'||vt==='douyin'){document.getElementById('pmVid').style.display='block';document.getElementById('pmVid').innerHTML='<div style="text-align:center;padding:20px;color:#aaa"><div style="font-size:48px;margin-bottom:12px">🔗</div><div style="margin-bottom:8px">'+t.name+'</div><a href="'+t.src+'" target="_blank" style="color:#007aff;font-size:14px;padding:8px 24px;border:1px solid #007aff;border-radius:20px;text-decoration:none">📥 在浏览器中打开</a></div>';_pAudio=null;document.getElementById('pmPlayBtn').textContent='▶️'}else{var src=t.src||t.data;var isV=/\.(mp4|webm|mov|mkv|avi)$/i.test(t.name||'');if(isV){document.getElementById('pmVid').style.display='block';document.getElementById('pmVid').innerHTML='<video id="pmVideo" src="'+src+'" style="width:100%;height:100%;object-fit:contain" controls ontimeupdate="pvtimeupdate()" onended="pnextTrack()"></video>';_pAudio=document.getElementById('pmVideo')}else{document.getElementById('pmVid').style.display='none';document.getElementById('pmVid').innerHTML='';_pAudio=new Audio(src);_pAudio.ontimeupdate=function(){var s=document.getElementById('pmSeek');var t=document.getElementById('pmTime');if(s&&t&&_pAudio){s.value=_pAudio.currentTime/_pAudio.duration*100||0;t.textContent=pft(_pAudio.currentTime)+' / '+pft(_pAudio.duration)}};_pAudio.onended=function(){pnextTrack()};_pAudio.play()}document.getElementById('pmPlayBtn').textContent='⏸'}prenderPlayer()}
function ptogglePlay(){if(!_pAudio)return;if(_pAudio.paused){_pAudio.play();document.getElementById('pmPlayBtn').textContent='⏸'}else{_pAudio.pause();document.getElementById('pmPlayBtn').textContent='▶️'}}
function pstop(){if(_pAudio){_pAudio.pause();_pAudio=null}var ve=document.getElementById('pmVid');if(ve)ve.innerHTML='';ve.style.display='none'}
function pseek(v){if(!_pAudio||!_pAudio.duration)return;_pAudio.currentTime=v/100*_pAudio.duration}
function pvtimeupdate(){var v=document.getElementById('pmVideo');if(!v)return;var s=document.getElementById('pmSeek');var t=document.getElementById('pmTime');if(s)s.value=v.currentTime/v.duration*100||0;if(t)t.textContent=pft(v.currentTime)+' / '+pft(v.duration)}
function pft(sec){if(!sec||isNaN(sec))return'0:00';var m=Math.floor(sec/60),s=Math.floor(sec%60);return m+':'+(s<10?'0':'')+s}
async function pnextTrack(){var a=[];try{a=await idbGet('pent_music')||[]}catch(ex){}if(!a.length)return;var next=_pcurTrack===null||_pcurTrack>=a.length-1?0:_pcurTrack+1;pplayTrack(next)}
async function pprevTrack(){var a=[];try{a=await idbGet('pent_music')||[]}catch(ex){}if(!a.length)return;var prev=_pcurTrack===null||_pcurTrack<=0?a.length-1:_pcurTrack-1;pplayTrack(prev)}
async function pshuffleAll(){var a=[];try{a=await idbGet('pent_music')||[]}catch(ex){}if(!a.length)return;var i=Math.floor(Math.random()*a.length);pplayTrack(i)}
function prenderPlayer(){var el=document.getElementById('pmPlayer');if(el)el.style.display='block';var n=document.getElementById('pmNow');if(n){idbGet('pent_music').then(function(d){var a=d||[];if(_pcurTrack!==null&&a[_pcurTrack])n.textContent='▶ '+a[_pcurTrack].name})}}
