// weather

function pgetWeather(){var seed=parseInt(new Date().toISOString().split('T')[0].replace(/-/g,''))%100;var conditions=[{e:'☀️',t:'晴',h:28,l:18},{e:'⛅',t:'多云',h:25,l:16},{e:'🌧️',t:'小雨',h:22,l:14},{e:'⛈️',t:'雷阵雨',h:24,l:15},{e:'🌤️',t:'晴间多云',h:26,l:17},{e:'☁️',t:'阴',h:23,l:15},{e:'🌦️',t:'阵雨',h:21,l:13},{e:'🌫️',t:'雾',h:20,l:12}];var today=conditions[seed%conditions.length];var tH=today.h+Math.floor(seed%5)-2;var tL=today.l+Math.floor(seed%5)-2;var fh='';var fc=['明天','后天','大后天'];for(var i=0;i<3;i++){var ci=conditions[(seed+i+1)%conditions.length];var fhH=ci.h+Math.floor((seed+i)%5)-2;var fhL=ci.l+Math.floor((seed+i)%5)-2;fh+='<div style="text-align:center;font-size:13px">'+fc[i]+'<br>'+ci.e+'<br>'+fhH+'°/'+fhL+'°</div>'}return{icon:today.e,type:today.t,high:tH,low:tL,fh:fh}}

function prWeather(){var w=pgetWeather();document.getElementById('paWeatherB').innerHTML='<div style="text-align:center;padding:20px"><div style="font-size:72px">'+w.icon+'</div><div style="font-size:56px;font-weight:200">'+w.high+'°</div><div style="color:#aaa;font-size:16px">'+w.type+' · 最低 '+w.low+'°</div></div><div style="display:flex;justify-content:space-around;padding:16px">'+w.fh+'</div><div style="text-align:center;font-size:11px;color:#555;margin-top:4px">📍 基于当日随机生成</div><button class="pent-btn" style="width:calc(100% - 24px);margin:8px 12px 0" onclick="pwxReal()">🌐 联网获取真实天气</button>'}

async function pwxReal(){var btn=document.querySelector('#paWeatherB .pent-btn');if(btn){btn.disabled=true;btn.textContent='⏳ 正在获取...'}try{var resp=await fetch('https://wttr.in/?format=j1&lang=zh',{signal:AbortSignal.timeout(8000)});if(!resp.ok)throw new Error('HTTP '+resp.status);var data=await resp.json();var cur=data.current_condition[0];var loc=data.nearest_area[0];var temp=cur.temp_C;var feels=cur.FeelsLikeC;var desc=cur.lang_zh&&cur.lang_zh[0]&&cur.lang_zh[0].value?cur.lang_zh[0].value:(cur.weatherDesc[0]?cur.weatherDesc[0].value:cur.weatherDesc[0].value);var code=cur.weatherCode;var icon=pwxIcon(code);var forecast='';var days=data.weather.slice(0,3);var fc=['今天','明天','后天'];for(var i=0;i<days.length;i++){var d=days[i];forecast+='<div style="text-align:center;font-size:13px">'+fc[i]+'<br>'+pwxIcon(d.hourly[6].weatherCode)+'<br>'+d.mintempC+'°/'+d.maxtempC+'°</div>'}var h='<div style="text-align:center;padding:20px"><div style="font-size:12px;color:#888">'+loc.areaName[0].value+' · 实时天气</div><div style="font-size:72px">'+icon+'</div><div style="font-size:56px;font-weight:200">'+temp+'°</div><div style="color:#aaa;font-size:16px">'+desc+' · 体感 '+feels+'°</div></div><div style="display:flex;justify-content:space-around;padding:16px">'+forecast+'</div><button class="pent-btn" style="width:calc(100% - 24px);margin:0 12px 8px" onclick="prWeather()">🔄 返回随机天气</button>';document.getElementById('paWeatherB').innerHTML=h}catch(e){if(btn){btn.disabled=false;btn.textContent='🌐 联网获取真实天气'}pnotify({title:'❌ 获取失败',text:'请检查网络后重试',icon:'⚠️'})}}

function pwxIcon(code){var m={113:'☀️',116:'⛅',119:'☁️',122:'☁️',143:'🌫️',176:'🌧️',179:'🌧️',182:'🌧️',185:'🌧️',200:'⛈️',227:'🌨️',230:'🌨️',248:'🌫️',260:'🌫️',263:'🌧️',266:'🌧️',281:'🌧️',284:'🌧️',293:'🌧️',296:'🌧️',299:'🌧️',302:'🌧️',305:'🌧️',308:'🌧️',311:'🌧️',314:'🌧️',317:'🌧️',320:'🌧️',323:'🌨️',326:'🌨️',329:'🌨️',332:'🌨️',335:'🌨️',338:'🌨️',350:'🌨️',353:'🌧️',356:'🌧️',359:'🌧️',362:'🌨️',365:'🌨️',368:'🌨️',371:'🌨️',374:'🌧️',377:'🌧️',386:'⛈️',389:'⛈️',392:'🌨️',395:'🌨️'};return m[code]||'🌤️'}
