function pgameminesweeper(){
var ov=document.createElement("div");
ov.style.cssText="position:fixed;inset:0;z-index:999999;background:rgba(0,0,0,.92);display:flex;flex-direction:column;align-items:center;justify-content:center";
ov.onclick=function(e){if(e.target===ov)ov.remove()};
var rows=9,cols=9,mines=10,board=[],revealed=[],flagged=[],gameOver=false,remaining=rows*cols-mines,flagMode=false;
function init(){board=[];revealed=[];flagged=[];gameOver=false;remaining=rows*cols-mines;for(var i=0;i<rows*cols;i++)board[i]=0;var placed=0;while(placed<mines){var r=Math.floor(Math.random()*rows),c=Math.floor(Math.random()*cols);var idx=r*cols+c;if(board[idx]===0){board[idx]=9;placed++}}for(var r2=0;r2<rows;r2++){for(var c2=0;c2<cols;c2++){var idx2=r2*cols+c2;if(board[idx2]===9)continue;var cnt=0;for(var dr=-1;dr<=1;dr++)for(var dc=-1;dc<=1;dc++){var nr=r2+dr,nc=c2+dc;if(nr>=0&&nr<rows&&nc>=0&&nc<cols&&board[nr*cols+nc]===9)cnt++}board[idx2]=cnt}}}
function reveal(r,c){if(r<0||r>=rows||c<0||c>=cols)return;var idx=r*cols+c;if(revealed[idx]||flagged[idx])return;revealed[idx]=true;remaining--;if(board[idx]===9){gameOver=true;return}if(board[idx]===0){for(var dr=-1;dr<=1;dr++)for(var dc=-1;dc<=1;dc++)reveal(r+dr,c+dc)}}
function render(){var h="<div style=color:#fff;font-size:24px;margin-bottom:4px>💣 扫雷</div>";
h+="<div style=color:#aaa;font-size:14px;margin-bottom:6px>雷:"+mines+" · 剩:"+remaining+(gameOver?" · <span style=color:#f44>踩雷了</span>":"")+"</div>";h+="<div style=margin-bottom:6px><button id=msMode style=padding:6px 16px;border-radius:14px;border:none;background:"+(flagMode?"#ff9500":"rgba(255,255,255,.15)")+";color:"+(flagMode?"#000":"#fff")+";font-size:13px;cursor:pointer;font-weight:600>🚩 标旗模式:"+(flagMode?"开":"关")+"</button></div>";
h+="<div id=msGrid style=display:grid;grid-template-columns:repeat("+cols+",34px);gap:2px;background:rgba(255,255,255,.05);padding:4px;border-radius:8px>";
for(var r=0;r<rows;r++){for(var c=0;c<cols;c++){var idx=r*cols+c;var cls="width:34px;height:34px;display:flex;align-items:center;justify-content:center;font-size:15px;border-radius:3px;cursor:pointer;font-weight:600";if(revealed[idx]){cls+=";background:"+(board[idx]===9?"#ff3b30":"rgba(255,255,255,.2)")+";color:"+(board[idx]===1?"#4da3ff":board[idx]===2?"#34c759":board[idx]===3?"#ff9500":"#fff")}else{cls+=";background:"+(flagged[idx]?"#ff9500":"rgba(255,255,255,.1)")}var content=revealed[idx]?(board[idx]===9?"💣":board[idx]>0?board[idx]:""):(flagged[idx]?"🚩":"");h+="<div data-idx="+idx+" style=\""+cls+"\">"+content+"</div>"}}
h+="</div>";
h+="<div style=margin-top:8px;display:flex;gap:8px><button id=msNew style=padding:8px 24px;border-radius:16px;border:none;background:#007aff;color:#fff;font-size:14px;cursor:pointer>🔄 新游戏</button><button onclick=this.parentElement.parentElement.remove() style=padding:8px 24px;border-radius:16px;border:none;background:rgba(255,255,255,.1);color:#888;font-size:14px;cursor:pointer>关闭</button></div>";
ov.innerHTML=h;var cells=ov.querySelectorAll("[data-idx]");for(var i=0;i<cells.length;i++){cells[i].onclick=function(){if(gameOver)return;var idx=parseInt(this.getAttribute("data-idx"));if(flagMode){if(!revealed[idx]){flagged[idx]=!flagged[idx];render()}}else{reveal(Math.floor(idx/cols),idx%cols);render()}};cells[i].oncontextmenu=function(e){e.preventDefault();if(gameOver)return;var idx=parseInt(this.getAttribute("data-idx"));if(!revealed[idx]){flagged[idx]=!flagged[idx];render()}}}var mb=document.getElementById("msMode");if(mb)mb.onclick=function(){flagMode=!flagMode;render()};var nb=document.getElementById("msNew");if(nb)nb.onclick=function(){ov.remove();setTimeout(function(){pgameminesweeper()},50)}
if(remaining===0&&!gameOver){pnotify({title:"🏆 扫雷胜利！",icon:"🏆"})}
}
document.body.appendChild(ov);init();render()}