function pgamesnake(){
var ov=document.createElement("div");
ov.style.cssText="position:fixed;inset:0;z-index:999999;background:rgba(0,0,0,.92);display:flex;flex-direction:column;align-items:center;justify-content:center";
ov.onclick=function(e){if(e.target===ov)ov.remove()};
var cols=10,rows=10,cell=Math.floor(Math.min(320,window.innerWidth-30)/cols);
var snake=[{x:5,y:5}],dir={x:1,y:0},nextDir={x:1,y:0},food=null,score=0,gameOver=false,timer=null,speed=220;
function spawnFood(){while(true){var fx=Math.floor(Math.random()*cols),fy=Math.floor(Math.random()*rows);var hit=false;for(var i=0;i<snake.length;i++){if(snake[i].x===fx&&snake[i].y===fy){hit=true;break}}if(!hit){food={x:fx,y:fy};break}}}
function turn(d){if(gameOver)return;if(d===0&&nextDir.y!==1){nextDir={x:0,y:-1}}else if(d===1&&nextDir.y!==-1){nextDir={x:0,y:1}}else if(d===2&&nextDir.x!==1){nextDir={x:-1,y:0}}else if(d===3&&nextDir.x!==-1){nextDir={x:1,y:0}}}
function render(){var h="<div style=color:#fff;font-size:22px;margin-bottom:4px>🐍 贪吃蛇 <span style=font-size:14px;color:#aaa>得分:"+score+"</span></div>";
h+="<div style=display:grid;grid-template-columns:repeat("+cols+","+cell+"px);grid-template-rows:repeat("+rows+","+cell+"px);background:rgba(255,255,255,.05);padding:3px;border-radius:6px>";
for(var y=0;y<rows;y++){for(var x=0;x<cols;x++){var isHead=snake[0].x===x&&snake[0].y===y;var isBody=false;for(var b=1;b<snake.length;b++){if(snake[b].x===x&&snake[b].y===y){isBody=true;break}}var isFood=food&&food.x===x&&food.y===y;var bg=isHead?"#34c759":isBody?"#2e9e54":"rgba(255,255,255,.06)";var content=isFood?"🍎":"";h+="<div style=width:"+cell+"px;height:"+cell+"px;display:flex;align-items:center;justify-content:center;font-size:"+(cell*0.6)+"px;background:"+bg+";border-radius:2px>"+content+"</div>"}}
h+="</div>";
h+="<div style=display:grid;grid-template-columns:repeat(3,44px);gap:4px;margin-top:8px><span></span><button data-dir=0 style=font-size:16px;padding:4px;border:none;border-radius:6px;background:rgba(255,255,255,.15);color:#fff;cursor:pointer>▲</button><span></span><button data-dir=2 style=font-size:16px;padding:4px;border:none;border-radius:6px;background:rgba(255,255,255,.15);color:#fff;cursor:pointer>◀</button><button data-dir=1 style=font-size:16px;padding:4px;border:none;border-radius:6px;background:rgba(255,255,255,.15);color:#fff;cursor:pointer>▼</button><button data-dir=3 style=font-size:16px;padding:4px;border:none;border-radius:6px;background:rgba(255,255,255,.15);color:#fff;cursor:pointer>▶</button><span></span></div>";
h+="<div style=margin-top:8px;display:flex;gap:8px>"+(gameOver?"<button id=snRestart style=padding:6px 20px;border-radius:14px;border:none;background:#34c759;color:#fff;font-size:13px;cursor:pointer>🔄 重玩</button>":"")+"<button onclick=this.parentElement.parentElement.remove() style=padding:6px 20px;border-radius:14px;border:none;background:#007aff;color:#fff;font-size:13px;cursor:pointer>关闭</button></div>";
ov.innerHTML=h;ov.querySelectorAll("[data-dir]").forEach(function(btn){btn.onclick=function(e){e.stopPropagation();turn(parseInt(this.getAttribute("data-dir")))}});var rst=document.getElementById("snRestart");if(rst)rst.onclick=function(e){e.stopPropagation();ov.remove();setTimeout(function(){pgamesnake()},50)}}
function step(){if(gameOver)return;var hx=snake[0].x+dir.x,hy=snake[0].y+dir.y;if(hx<0||hx>=cols||hy<0||hy>=rows){gameOver=true;render();return}for(var i=0;i<snake.length;i++){if(snake[i].x===hx&&snake[i].y===hy){gameOver=true;render();return}}snake.unshift({x:hx,y:hy});if(food&&hx===food.x&&hy===food.y){score++;speed=Math.max(70,220-score*5);spawnFood();clearInterval(timer);timer=setInterval(loop,speed)}else{snake.pop()}render()}
function loop(){dir={x:nextDir.x,y:nextDir.y};step()}
try{document.body.appendChild(ov);spawnFood();render();timer=setInterval(loop,speed);document.addEventListener("keydown",function sk(e){if(!document.body.contains(ov)){document.removeEventListener("keydown",sk);return}var k=e.key;if(k==="ArrowUp")turn(0);else if(k==="ArrowDown")turn(1);else if(k==="ArrowLeft")turn(2);else if(k==="ArrowRight")turn(3)})}catch(err){pnotify({title:"贪吃蛇启动失败",text:err.message,icon:"⚠️"})}
}